name: My cicd pipeline in github action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: First Step
        run: |
          echo "this is DEVops commit first"
          uname -a







      
      




